import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* header */}
      <body className='px-5 md:px-10'>
        <header className='w-full h-[64px] bg-red-500'></header>
        {children}
        {/* <footer className='w-full h-[260px] bg-blue-500'></footer> */}
      </body>
    </html>
  );
}
